version: 2
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - bench:
          requires:
            - build
          filters:
            branches:
              only: /^(?!pull\/).*$/
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Run tests
          command: yarn test

      # test the bundlesize
      - run:
          name: Test bundlesize
          command: yarn test:bundlesize

  bench:
    docker:
      - image: ameerthehacker/brahmos-automated-benchmark:v0.0.1
    steps:
      - run:
          name: Benchmark brahmos
          command: sh bench.sh
