version: 2
workflows:
  version: 2
  build_and_bench:
    jobs:
      - build
      - bench:
          requires:
            - build
          filters:
            branches:
              only: /pull\/[0-9]+/
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Run tests
          command: yarn test

      # test the bundlesize
      - run:
          name: Test bundlesize
          command: yarn test:bundlesize

      # Build Brahmos
      - run:
          name: Build Brahmos
          command: yarn bundle     

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is 
          # taken to be the root directory of the workspace.
          root: .
          # Must be relative path from root
          paths:
            - package.json
            - dist       

  bench:
    docker:
      - image: ameerthehacker/brahmos-automated-benchmark:v0.0.1
    steps:
      - attach_workspace:
          at: /benchmarking-tool/frameworks/keyed/brahmos/lib
      - run:
          name: Benchmark brahmos
          command: sh /benchmarking-tool/bench.sh 5
          